import Head from "next/head";
import React from "react";
import Categories from "../../components/Categories";
import Footer from "../../components/Footer";
import Nav from "../../components/Nav";
import Search from "../../components/Search";

const search = ({ data }) => {
  return (
    <div>
      <Head>
        <title>Seach Results</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="">
        <Nav />
        <div className="max-w-6xl mx-auto ">
          <Categories />
          <Search results={data} />
        </div>
        <Footer />
      </main>
    </div>
  );
};

export default search;

export async function getServerSideProps({ query }) {
  const { search } = query;
  console.log(search);

  const res = await fetch(
    `https://api.spoonacular.com/recipes/complexSearch?apiKey=${process.env.API_KEY}&query=${search}`
  );
  const data = await res.json();

  return {
    props: {
      data: data.results,
    },
  };
}
