import Head from "next/head";
import Categories from "../../components/Categories";
import Cusine from "../../components/Cusine";
import Nav from "../../components/Nav";
import Footer from "../../components/Footer";

const America = ({ data }) => {
  return (
    <div>
      <Head>
        <title></title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="">
        <Nav />
        <div className="max-w-6xl mx-auto ">
          <Categories />
          <Cusine results={data} />
        </div>
        <Footer />
      </main>
    </div>
  );
};

export default America;

export async function getServerSideProps({ query }) {
  const { id } = query;

  const res = await fetch(
    `https://api.spoonacular.com/recipes/complexSearch?apiKey=${process.env.API_KEY}&cuisine=${id}`
  );
  const data = await res.json();

  return {
    props: {
      data: data.results,
    },
  };
}
